name: build and test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: ubuntu (mruby-${{matrix.TARGET_MRUBY}})
    strategy:
      matrix:
        TARGET_MRUBY:
        - master
        - 3.4.0
        - 3.3.0
        - 3.2.0
        - 3.1.0
        - 3.0.0
    env:
      MRUBY_URL: "https://github.com/mruby/mruby/archive/${{matrix.TARGET_MRUBY}}.tar.gz"
      MRUBY_DIR: "mruby-${{matrix.TARGET_MRUBY}}"
    steps:
    - uses: actions/checkout@v5
    - name: fetch and extract mruby
      run: wget -O- $MRUBY_URL | tar xzf -
    - name: build
      run: rake -vf $MRUBY_DIR/Rakefile MRUBY_CONFIG=test_config.rb
    - name: test
      run: rake -vf $MRUBY_DIR/Rakefile MRUBY_CONFIG=test_config.rb test
